---

- name: Install docker
  become: yes
  apt:
    name: "docker.io"
  tags:
    - docker

- name: Ensure ubuntu is added to the docker group
  user:
    name: "ubuntu"
    groups: docker
    append: true
  tags:
  - docker
