---

- name: Create project directory
  become: yes
  file:
    path: "{{ app_root_dir }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true
  tags:
    - deploy

- name: Clone/Pull git repository
  git:
    repo: "{{ app_repo_remote }}"
    dest: "{{ app_root_dir }}"
    version: "{{ app_repo_branch }}"
    accept_hostkey: yes
    force: yes
  tags:
    - deploy

- name: Create directory for logs
  become: yes
  file:
    path: "{{ app_log_dir }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true
  tags:
    - deploy

- name: Create run directory
  become: yes
  file:
    path: "{{ app_run_dir }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true
  tags:
    - deploy

- name: Install PIP dependencies
  pip:
    requirements: "{{ app_root_dir }}/requirements/requirements.txt"
    virtualenv: "{{ app_venv_dir }}"
    virtualenv_command: /usr/bin/python3.6 -m venv
  args:
    chdir: "{{ app_root_dir }}"
  tags:
    - deploy

- name: Add env file
  become: yes
  template:
    src: templates/env
    dest: "{{ app_root_dir }}/.env"
  tags:
    - deploy

- name: Execute migrations
  command: "{{ app_venv_dir }}/bin/python manage.py migrate"
  register: db_migrations_result
  changed_when: "db_migrations_result.stdout is not search('No migrations to apply')"
  args:
    chdir: "{{ app_root_dir }}"
  tags:
    - deploy
    - migration

#- name: Create an initial superuser
#  django_manage:
#    command: "createsuperuser --noinput --email=masaha@mailinator.com"
#    virtualenv: "{{ app_venv_dir }}"
#    app_path: "{{ app_root_dir }}"

- name: Collect static files
  command: "{{ app_venv_dir }}/bin/python manage.py collectstatic --no-input"
  register: collectstatic_result
  changed_when: "collectstatic_result.stdout is not search('0 static files copied')"
  args:
    chdir: "{{ app_root_dir }}"
  tags:
    - deploy