# Generated by Django 2.1.2 on 2019-01-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
        ('core', '0003_auto_20181209_1238'),
    ]

    operations = [
    ]
