# Generated by Django 2.1.2 on 2019-01-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190109_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
