# Generated by Django 2.1.2 on 2018-12-20 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0004_auto_20181204_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cost', models.FloatField()),
                ('per_day', models.FloatField()),
                ('method', models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'Paypal'), ('KN', 'KNET')], default=None, max_length=10, null=True)),
                ('payment_type', models.CharField(choices=[('advertisement ad', 'advertisement ad')], default='advertisement ad', max_length=20)),
                ('currency', models.CharField(choices=[('KWD', 'KWD'), ('USD', 'USD')], default='KWD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=7)),
                ('knet_charge_id', models.CharField(max_length=256, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
