# Generated by Django 2.1.2 on 2019-02-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181128_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
