# Generated by Django 2.1.2 on 2018-11-27 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20181124_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
