# Generated by Django 2.1.2 on 2018-12-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181209_1238'),
        ('ads', '0004_auto_20181204_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City'),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_seller_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='premium_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.Category'),
        ),
    ]
