# Generated by Django 2.1.2 on 2018-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20181219_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=16)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_phone_number_confirmed', models.BooleanField(default=False)),
                ('email_confirmation_token', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('phone_number_confirmation_code', models.CharField(editable=False, max_length=64, null=True, unique=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
        ),
    ]
