# Generated by Django 2.1.2 on 2019-02-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarMakeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Car Makes',
            },
        ),
        migrations.CreateModel(
            name='CarModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.CarMakeCategory')),
            ],
            options={
                'verbose_name_plural': 'Car Makes',
            },
        ),
        migrations.CreateModel(
            name='MobileAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileBrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Brands',
            },
        ),
        migrations.CreateModel(
            name='MobileModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.MobileBrandCategory')),
            ],
            options={
                'verbose_name_plural': 'Mobile Models',
            },
        ),
        migrations.CreateModel(
            name='RealEstateAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('for_sale', 'FOR SALE'), ('for_sale', 'FOR RENT')], default='for_sale', max_length=16)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='mobilead',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.MobileBrandCategory'),
        ),
        migrations.AddField(
            model_name='mobilead',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.MobileModelCategory'),
        ),
        migrations.AddField(
            model_name='carad',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.CarMakeCategory'),
        ),
        migrations.AddField(
            model_name='carad',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.CarModelCategory'),
        ),
    ]
