# Generated by Django 2.1.2 on 2019-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20190226_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodelcategory',
            options={'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterField(
            model_name='realestatead',
            name='purpose',
            field=models.CharField(choices=[('for_sell', 'FOR SELL'), ('for_rent', 'FOR RENT')], default='for_sell', max_length=16),
        ),
    ]
