# Generated by Django 2.1.7 on 2019-03-23 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_internal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carad',
            name='body_style',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('wagon', 'Wagon'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('suv/truck', 'SUV/Truck'), ('pickup truck', 'Pickup Truck'), ('minivan/minibus', 'Minivan/Minibus'), ('van', 'Van'), ('limousine', 'Limousine')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carad',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)]),
        ),
        migrations.AddField(
            model_name='realestatead',
            name='bathrooms',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='realestatead',
            name='bedrooms',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='realestatead',
            name='estate_type',
            field=models.CharField(choices=[('shop', 'Shop'), ('apartment', 'Apartment'), ('villa', 'Villa')], default=None, max_length=16, null=True),
        ),
    ]
