# Generated by Django 2.1.7 on 2019-03-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20190323_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='internal_url',
            new_name='external_url',
        ),
    ]
