# Generated by Django 2.1.7 on 2019-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20190325_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelcategory',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='carmodelcategory',
            unique_together={('name', 'make')},
        ),
    ]
