# Generated by Django 2.1.7 on 2019-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20190326_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemodelcategory',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='mobilemodelcategory',
            unique_together={('name', 'brand')},
        ),
    ]
