---

- name: Initial configuration for a project server
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  gather_facts: no
  vars_files:
  - ./vars/vars.yml

  pre_tasks:

    - name: Install python2 for ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  roles:
    - security