---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: "{{ server_user }}"
  gather_facts: no

  vars_files:
  - ./vars/vars.yml

  vars_prompt:

  - name: "su_email"
    prompt: "Enter an email"
    private: no

  - name: "su_password"
    prompt: "Enter a password"
    private: yes


  tasks:
  - name: Create superuser
    shell: echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('{{ su_email }}', '{{ su_password }}')" | {{app_venv_dir}}/bin/python manage.py shell
    args:
      chdir: "{{app_root_dir}}/"